apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Name }}-{{ .Values.namespace.name }}
  labels:
    {{- range $key, $value := .Values.namespace.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}