apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mef-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
