#apiVersion: autoscaling/v2
  #kind: HorizontalPodAutoscaler
  #metadata:
  #  name: elaboration-timb-ms-autoscaling
  #  namespace: tm-gla
  #spec:
  #  scaleTargetRef:
  #    apiVersion: apps/v1
  #    kind: Deployment
  #    name: elaboration-timb-ms-deployment
  #  minReplicas: 1
  #  maxReplicas: 4
  #  metrics:
  #    - type: Resource
  #      resource:
  #        name: cpu
  #        target:
  #          type: Utilization
  #          averageUtilization: 60
  #  behavior:
  #    scaleDown:
  #      stabilizationWindowSeconds: 120
  #      policies:
  #        - type: Pods
  #          value: 4
  #          periodSeconds: 60
  #        - type: Percent
  #          value: 10
  #          periodSeconds: 60
  #    scaleUp:
  #      stabilizationWindowSeconds: 0
  #      policies:
  #        - type: Percent
  #          value: 100
  #          periodSeconds: 15
  #        - type: Pods
  #          value: 4
  #          periodSeconds: 15
  #      selectPolicy: Max
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: elaboration-timb-ms-scaled
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: elaboration-timb-ms-deployment
  cooldownPeriod: 600
  maxReplicaCount:  4
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 600
          policies:
            - type: Percent
              value: 50
              periodSeconds: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: "{{ .Values.kafka.bootstrapServers }}"
        consumerGroup: {{ .Values.kafka.consumerGroup }}
        topic: {{ .Values.kafka.topic }}
        lagThreshold: '6'
        offsetResetPolicy: earliest
