apiVersion: v1
kind: Service
metadata:
  name: scheduled-client-entrypoint
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.scheduledClient.service.type }}
  selector:
    app: scheduled-client
  ports:
    - port: {{ .Values.scheduledClient.service.port }}
      targetPort: {{ .Values.scheduledClient.service.targetPort }}
      protocol: TCP
      name: http
{{ if (and (eq .Values.scheduledClient.service.type "NodePort") (not (empty .Values.scheduledClient.service.nodePort))) }}
      nodePort: {{.Values.scheduledClient.service.nodePort }}
{{ end }}
