apiVersion: v1
kind: Service
metadata:
  name: scheduled-client-entrypoint
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.scheduledClient.service.type }}
  selector:
    app: scheduled-client
  ports:
    - port: {{ .Values.scheduledClient.service.port }}
      targetPort: {{ .Values.scheduledClient.service.port }}
      nodePort: {{ .Values.scheduledClient.service.nodePort }}
      protocol: TCP
