namespace: uc1-workload

persistentVolumeClaim:
  storage: 5Gi
  storageClassName: longhorn

kafka:
  bootstrapServers: 'kafka.kafka.svc.cluster.local:9092'
  consumerGroup: 'uc1-workload'
  topic: test
  listenerPartitions: 12
  listenerConcurrency: 12

scheduledClient:
  image: 'ghcr.io/glaciation-heu/mef-sog-uc1/scheduled-client:1.1.0'
  service:
    type: NodePort
    port: 8080
    nodePort: 30001

elaborationTimbMs:
  image: 'ghcr.io/glaciation-heu/mef-sog-uc1/elaboration-timb-ms:1.0.0'
