namespace:
  name: mef-sog-uc1-wl
  labels:
    create-ca-bundle: 'true'

timeZone: 'Europe/Rome'

persistentVolumeClaim:
  storage: 5Gi
  storageClassName: longhorn

kafka:
  bootstrapServers: 'kafka.kafka.svc.cluster.local:9092'
  consumerGroup: 'mef-sog-uc1-wl'
  topic: flusso-default
  topicExtra: flusso-encrypt
  listener:
    partitions: 12
    concurrency: 12
  consumer:
    maxPollRecords: 1
    maxPollIntervalMs: 300000

scheduledClient:
  kafkaEnabled: 'true'
  image: 'ghcr.io/glaciation-heu/mef-sog-uc1/scheduled-client:2.0.1'
  multipartMaxFileSize: '500MB'
  watchingFolderSeconds: 1
  service:
    type: NodePort
    port: 8080
    targetPort: http
    nodePort: 30001
  resources:
    requests:
      memory: '1Gi'
      cpu: '500m'
      nvidiaGpu: '0'
      ephemeralStorage: '1Mi'
    limits:
      memory: '1Gi'
      cpu: '1'
      nvidiaGpu: '0'
      ephemeralStorage: '20Mi'

elaborationTimbMs:
  image: 'ghcr.io/glaciation-heu/mef-sog-uc1/elaboration-timb-ms:2.0.3'
  logLevelJpa: false
  h2Console: false
  metricsEnabled: false
  resources:
    requests:
      memory: '1Gi'
      cpu: '500m'
      nvidiaGpu: '0'
      ephemeralStorage: '20Mi'
    limits:
      memory: '1Gi'
      cpu: '1'
      nvidiaGpu: '0'
      ephemeralStorage: '200Mi'
  deployment:
    default:
      scaling:
        maxReplicaCount: 2
      minio:
        enabled: true
        bucket: uc1-mef-sog-default
        subPath: ""
    encrypt:
      scaling:
        maxReplicaCount: 2
      minio:
        enabled: true
        bucket: uc1-mef-sog-encrypt
        subPath: ""
    serverMinio:
      endpoint: https://minio.data-wrapping.svc.cluster.local
      credentials:
        accessKey: minio
        secretKey: minio123

volume:
  mountPath: '/MEF/'
  path:
    timbrature: '/MEF/file/timbrature'
    toBeElaborated: '/MEF/file/to-be-elaborated'
    elaborated: '/MEF/file/elaborated'
    acquired: '/MEF/file/completed'
    discarded: '/MEF/file/discarded'
    metrics: '/MEF/metrics'
