spring:
    application:
        name: elaboration-timb-ms
    datasource:
        driver-class-name: org.h2.Driver
        password: ${SPRING_DATASOURCE_PASSWORD:gla_passw}
        url: jdbc:h2:mem:mydb
        username: ${SPRING_DATASOURCE_USERNAME:gla_usr}
    h2:
        console:
            enabled: ${H2_CONSOLE:true}
            path: /h2-console
            settings.trace: false
            settings.web-allow-others: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        properties.hibernate.format_sql: ${LOG_LEVEL_JPA:true}
        show-sql: ${LOG_LEVEL_JPA:true}
    kafka:
        consumer:
            bootstrap-servers: ${SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS:${spring.embedded.kafka.brokers}}
            group-id: ${SPRING_KAFKA_CONSUMER_GROUP-ID:tm-gla}
            auto-offset-reset: earliest
            max-poll-records: ${SPRING_KAFKA_CONSUMER_MAX-POLL-RECORDS:500}
            properties:
                max-poll-interval-ms: ${SPRING_KAFKA_CONSUMER_MAX-POLL-INTERVAL-MS:300000}
                spring:
                    json:
                        add.type.headers: false
        listener:
            topic: ${SPRING_KAFKA_LISTENER_TOPIC:timbrature}
            concurrency: ${SPRING_KAFKA_LISTENER_CONCURRENCY:1}
            partitions: ${SPRING_KAFKA_LISTENER_PARTITIONS:1}
server:
    port: 8081
    servlet:
        context-path: /elaboration-timb-ms
path:
    timbrature.elaborated: ${PATH_TIMESTAMPS_ELABORATED:C:\MEF\file\elaborated}
    timbrature.completed: ${PATH_TIMESTAMPS_ACQUIRED:C:\MEF\file\completed}
    timbrature.discarded: ${PATH_TIMESTAMPS_DISCARDED:C:\MEF\file\discarded}
    metrics: ${PATH_METRICS:C:\MEF\file\metrics}

metrics:
    enabled: ${METRICS_ENABLED:false}
    
management:
    endpoints:
        web:
            exposure:
                include:
                  - prometheus
                  - health
                  - info
                  - metric

minio:
    enabled: ${MINIO_ENABLED:false}
    endpoint: ${MINIO_ENDPOINT:https://glaciation-tenant.integration}
    bucket: ${MINIO_BUCKET:uc1}
    subPathBucket: ${MINIO_SUB_PATH_BUCKET:/mef-sog/}
    credentials:
        accessKey: ${MINIO_CREDENTIALS_ACCESSKEY:hXhsTQ9lN4Jbki7Ydm7Z}
        secretKey: ${MINIO_CREDENTIALS_SECRETKEY:U2ZD4qygrx4EApjg3fmHfCIm6IjvxDTNgErrw9bI}