version: '3.8'

services:
  nginx:
    image: nginx:1.24.0
    container_name: nginx
    restart: always
    ports:
      - "8081:80"
    volumes:
      - /home/ubuntu/nginx/conf.d/:/etc/nginx/conf.d/
