apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop-deployment
  namespace: kafka
  labels:
    app: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/kafdrop"

---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-entrypoint
  namespace: kafka
spec:
  selector:
    app: kafdrop
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30010
      protocol: TCP
  type: NodePort
