spring:
    application:
        name: scheduled-client
    kafka:
        enabled: ${SPRING_KAFKA_ENABLED:true}
        producer:
            bootstrap-servers: ${SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS:vmmeftmsrv.inmatica.com:9092}
            topic: ${SPRING_KAFKA_PRODUCER_TOPIC:timbrature}
    servlet:
        multipart:
            max-file-size: ${SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE:200MB}
            max-request-size: ${SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE:200MB}

swagger:
    basePackage: it.mef.tm
    descrizione: Glaciation experimentation - Scheduleds service for the acquisition of timestamps
    titolo: Scheduled client
    versione: 1.0.0

path:
    timbrature: ${PATH_TIMESTAMPS:C:\MEF\file\timbrature}
    timbrature.to-be-elaborated: ${PATH_TIMESTAMPS_TO-BE-ELABORATED:C:\MEF\file\to-be-elaborated}

server:
    port: 8080
    servlet:
        context-path: /scheduled-client

fixedRate.watching.folder.seconds: ${FIXEDRATE_WATCHING_FOLDER_SECONDS:5}

management:
    endpoints:
        web:
            exposure:
                include:
                  - prometheus
                  - health
                  - info
                  - metric
                  
