spring:
    application:
        name: scheduled-client
    kafka:
        enabled: true
        producer:
            bootstrap-servers: PLAINTEXT://localhost:9092
            topic: timbrature
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 200MB

swagger:
    basePackage: it.mef.tm
    descrizione: Glaciation experimentation - Scheduled services for the acquisition of timestamps
    titolo: Scheduled client
    versione: 1.0.0

path:
    timbrature: ${java.io.tmpdir}timbrature
    timbrature.to-be-elaborated: ${java.io.tmpdir}acquisite

server:
    port: 8080
    servlet:
        context-path: /scheduled-client

fixedRate.watching.folder.seconds: 3

management:
    endpoints:
        web:
            exposure:
                include: [ "prometheus" ]