image:
  tag: 3.5.1-debian-11-r25
  pullPolicy: Always

kraft:
  enabled: false

auth:
  interBrokerProtocol: plaintext

broker:
  replicaCount: 3
  podAntiAffinityPreset: hard
  persistence:
    enabled: true
    storageClass: longhorn
    accessModes:
      - ReadWriteOnce
    size: 2Gi
#  customConfig:
#    offsetsTopicReplicationFactor: 1
#    transactionStateLogReplicationFactor: 1
#    transactionStateLogMinIsr: 1

controller:
  replicaCount: 0

zookeeper:
  enabled: true
  replicaCount: 3
  podAntiAffinityPreset: hard
  persistence:
    enabled: true
    storageClass: longhorn
    accessModes:
      - ReadWriteOnce
    size: 5Gi

listeners:
  client:
    protocol: plaintext

  interbroker:
    protocol: plaintext

  external:
    protocol: plaintext

externalAccess:
  enabled: false
