name: Docker Series Builds

on:
  push:
    paths:
      - workload-core/scheduled-client/**
      - workload-core/elaboration-timb-ms/**
#on:
#  push:
#    branches: [ "main" ]
#    # Publish semver tags as releases.
##    tags: [ 'v*.*.*' ]
#  pull_request:
#    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: ${{ env.DOCKER_TAGS }}

    - name: Build and push docker image scheduled-client
      uses: docker/build-push-action@v6
      with:
        push: true
#        tags: ${{ env.DOCKER_IMAGES }}
        tags: "ghcr.io/glaciation-heu/mef-sog-uc1/scheduled-client:2.0.1"
#        labels: ${{ steps.meta.outputs.labels }}
        context: "${{ github.workspace }}/workload-core/scheduled-client"

    - name: Build and push docker image elaboration-timb-ms
      uses: docker/build-push-action@v6
      with:
        push: true
#        tags: ${{ env.DOCKER_IMAGES }}
        tags: "ghcr.io/glaciation-heu/mef-sog-uc1/elaboration-timb-ms:2.0.3"
#        labels: ${{ steps.meta.outputs.labels }}
        context: "${{ github.workspace }}/workload-core/elaboration-timb-ms"
