name: Docker Series Builds

on: [push]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

#    - name: Extract Docker metadata
#      id: meta
#      uses: docker/metadata-action@v5
#      with:
#        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#        tags: ${{ env.DOCKER_TAGS }}

    - name: Build and push docker image scheduled-client
      uses: docker/build-push-action@v6
      with:
        push: true
#        tags: ${{ env.DOCKER_IMAGES }}
        tags: ghcr.io/scheduled-client:1.0.0
#        labels: ${{ steps.meta.outputs.labels }}
        context: "${{ github.workspace }}/workload-core/scheduled-client"

#    - name: docker build scheduled-client
#      run: |
#        docker build ./workload-core/scheduled-client -t mef-sog-uc1/scheduled-client:1.0.0
#    - name: docker build elaboration-timb-ms
#      run: |
#        docker build ./workload-core/elaboration-timb-ms -t mef-sog-uc1/elaboration-timb-ms:1.0.0
